- name: start docker
  service: name=docker state=started

- name: reload docker
  service: name=docker state=reloaded

- name: restart docker
  service: name=docker state=restart

- name: stop docker
  service: name=docker state=stopped
