- name: make sure pt-transport-https is installed
  apt: name=apt-transport-https state=installed

- name: add docker repo key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: add docker repo and update apt cache
  apt_repository: repo="deb http://get.docker.io/ubuntu docker main" update_cache=yes state=present

- name: install docker
  apt: name=lxc-docker state=present
  notify: 
    - start docker

- name: install docker-py
  pip: name=docker-py version=1.1.0 state=present
